config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :transport_models, only: %i[index new create show edit update show] do
    patch 'change_status', on: :member
  end
  resources :vehicles, only: %i[index new create update edit show] do
    get 'search', on: :collection
  end
  resources :price_by_distances, only: %i[new create edit update destroy]
  resources :price_by_weights, only: %i[new create edit update destroy]
  resources :delivery_time_table, only: %i[new create edit update destroy]
  resources :service_orders, only: %i[index new create show] do
    get 'search', on: :collection
    scope module: :service_orders, as: 'service_orders' do
      collection do
        resources :process, only: %i[index create edit]
        resources :deliver, only: %i[index create edit]
      end
    end
  end
end

app/models/transport_model.rb
# frozen_string_literal: true

class TransportModel < ApplicationRecord
  enum status: { active: 5, disabled: 10 }

  validates :minimum_distance, :maximum_distance, :minimum_weight, :maximum_weight, :fixed_rate, presence: true
  validates :minimum_distance, :maximum_distance, :fixed_rate, :minimum_weight,
            :maximum_weight, numericality: { greater_than_or_equal_to: 0, message: 'não pode ser negativa' }
  validates :name, uniqueness: true, presence: true

  has_many :vehicles
  has_many :price_by_distances
  has_many :price_by_weights
  has_many :delivery_time_tables
  has_many :service_orders

  scope :by_distance, lambda { |distance|
                        where('minimum_distance <= :distance AND maximum_distance >= :distance', distance:)
                      }
  scope :with_vehicles_available, -> { where(id: Vehicle.select(:transport_model_id).waiting) }

  def shipping_price(weight, distance)
    fixed_rate + tax_distance(distance) + tax_weight(weight, distance)
  end

  def tax_distance(distance)
    available_ranges = price_by_distances.where('start_range <= :distance AND end_range > :distance',
                                                distance:)
    return 0 if available_ranges.empty?

    available_ranges.first.distance_tax
  end

  def tax_weight(weight, distance)
    available_ranges = price_by_weights.where('start_range <= :weight AND end_range > :weight', weight:)
    return 0 if available_ranges.empty?

    available_ranges.first.price_for_kg * distance
  end

  def delivery_time(distance)
    available_ranges = delivery_time_tables.where('start_range <= :distance AND end_range > :distance',
                                                  distance:)
    return 0 if available_ranges.empty?

    available_ranges.first.delivery_time
  end
end

app/controllers/transport_models_controller.rb
# frozen_string_literal: true

class TransportModelsController < ApplicationController
  before_action :authenticate_user!
  def index
    @transport_models = TransportModel.all
  end

  def new
    @transport_model = TransportModel.new
  end

  def create
    @transport_model = TransportModel.new(transport_model_params)

    if @transport_model.save
      flash[:notice] = 'Modelo de Transporte cadastrado com sucesso.'
      redirect_to transport_model_path(@transport_model.id)
    else
      flash.now[:notice] = 'Modelo de Transporte não cadastrado.'
      render 'new'
    end
  end

  def edit
    @transport_model = TransportModel.find(params[:id])
  end

  def update
    @transport_model = TransportModel.find(params[:id])

    if @transport_model.update(transport_model_params)
      flash[:notice] = 'Modelo de Transporte atualizado com sucesso.'
      redirect_to transport_model_path(@transport_model.id)
    else
      flash.now[:notice] = 'Não foi possível atualizar o modelo de transporte.'
      render 'edit'
    end
  end

  def show
    @transport_model = TransportModel.find(params[:id])
    @transport_models = TransportModel.all
    @price_by_distances = PriceByDistance.where(transport_model_id: @transport_model.id).sort_by(&:start_range)
    @price_by_distance = PriceByDistance.new
    @price_by_weights = PriceByWeight.where(transport_model_id: @transport_model.id).sort_by(&:start_range)
    @price_by_weight = PriceByWeight.new
    @delivery_times_table = DeliveryTimeTable.where(transport_model_id: @transport_model.id).sort_by(&:start_range)
    @delivery_time_table = DeliveryTimeTable.new
  end

  def change_status
    transport_model = TransportModel.find(params[:id])
    if transport_model.active?
      transport_model.disabled!
      redirect_to transport_models_path, notice: "O Modelo #{transport_model.name} foi desativado."
    else
      transport_model.active!
      redirect_to transport_models_path, notice: "O Modelo #{transport_model.name} foi ativado."
    end
  end

  private

  def transport_model_params
    params.require(:transport_model).permit(
      :name, :minimum_distance,
      :maximum_distance, :minimum_weight, :maximum_weight, :fixed_rate
    )
  end
end

app/views/transport_models/_form.html.erb
<%= form_with(model: @transport_model) do | tm |%>
  <div class="mb-3">
    <%= tm.label :name %>
    <%= tm.text_field :name%>
  </div>
  <div class="mb-3">
    <%= tm.label :minimum_distance %>
    <%= tm.number_field :minimum_distance %>
  </div>
  <div class="mb-3">
    <%= tm.label :maximum_distance %>
    <%= tm.number_field :maximum_distance %>
  </div>
  <div class="mb-3">
    <%= tm.label :minimum_weight %>
    <%= tm.number_field :minimum_weight %>
  </div>
  <div class="mb-3">
    <%= tm.label :maximum_weight %>
    <%= tm.number_field :maximum_weight %>
  </div>
  <div class="mb-3">
    <%= tm.label :fixed_rate %>
    <%= tm.number_field :fixed_rate %>
  </div> 
  <div class="mb-3">
    <%= tm.submit 'Cadastrar'%>
  </div>
<% end %>

app/views/transport_models/edit.html.erb
<h2> Editar Modelo de Transporte</h2>

<% if @transport_model.errors.any? %>
  <p> Verifique os erros abaixo: </p>

  <ul>
    <% @transport_model.errors.full_messages.each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/transport_models/index.html.erb
<h2> <%=TransportModel.model_name.human%></h2>
<nav>
  <% if current_user.admin? %>
    <%= link_to 'Cadastrar novo modelo de transporte', new_transport_model_path %>
  <% end %>
</nav>

<% if @transport_models.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= TransportModel.model_name.human %></th>
        <th><%= TransportModel.human_attribute_name(:fixed_rate)%></th>
        <th><%= TransportModel.human_attribute_name(:status)%></th>
      </tr>
    </thead>
    <tbody>
      <% @transport_models.each do | tm | %>
      <tr>
        <td><%= link_to tm.name, tm %> </td>
        <td> <%= number_to_currency(tm.fixed_rate, unit: "R$", separator: ",") %></td>
        <% if current_user.admin? %>
          <td> <%= button_to I18n.t(tm.status), change_status_transport_model_path(tm.id), { method: 'patch', class:"btn btn-dark" } %> </td>
          <td> <%= link_to 'Editar', edit_transport_model_path(tm.id)%> </td>
        <% else %>
          <td> <%= I18n.t(tm.status) %> </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p>Nao existem modelos de transporte cadastrados.</p>
<% end %>

app/views/transport_models/new.html.erb
<h1> Novo Modelo de Transporte </h1>

<% if @transport_model.errors.any? %>
  <p> Verifique os erros abaixo: </p>

  <ul>
    <% @transport_model.errors.full_messages.each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/transport_models/show.html.erb
<h2> <%= TransportModel.model_name.human %>: <%=@transport_model.name%></h2>

<div>
  <dl>
    <dt> Intervalo de Distância aceitável:</dt>
    <dd> <%= @transport_model.minimum_distance %> - <%= @transport_model.maximum_distance %>km</dd>
    <dt> Intervalo de Peso suportável:</dt>
    <dd> <%= @transport_model.minimum_weight %> - <%= @transport_model.maximum_weight %>kg</dd>
    <dt> <%= TransportModel.human_attribute_name(:fixed_rate)%>:</dt>
    <dd> <%= number_to_currency(@transport_model.fixed_rate, unit: "R$", separator: ",") %></dd>
    <dt> <%= TransportModel.human_attribute_name(:status)%>:</dt>
    <dd><%= I18n.t(@transport_model.status) %></dd>
  </dl>
</div>

<h3>Taxa de Distância</h3>

<% if !flash[:price_by_distance_errors].nil? %>
  <p> Verifique os erros abaixo: </p>
  <ul>
    <% flash[:price_by_distance_errors].each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<div class="price_by_distance" id="form">
  <% if current_user.admin? %>
    <%= form_with(model: @price_by_distance) do | pd |%>
      <%= pd.hidden_field :transport_model_id, value: @transport_model.id, readonly: true %>
      <div class="mb-3">
        <%= pd.label :start_range %>
        <%= pd.number_field :start_range, required: true %>
      </div>
      <div class="mb-3">
        <%= pd.label :end_range %>
        <%= pd.number_field :end_range, required: true %>
      </div>
      <div class="mb-3">
        <%= pd.label :distance_tax%>
        <%= pd.number_field :distance_tax, step: 0.10, required: true %>
      </div>
      <div class="mb-3">
        <%= pd.submit 'Cadastrar Taxa por Distância', class:"btn btn-dark"%>
      </div>
    <% end %>
  <% end %>
</div>

<div>
  <% if @price_by_distances.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th> <%= PriceByDistance.human_attribute_name(:start_range)%></th>
          <th><%= PriceByDistance.human_attribute_name(:end_range)%></th>
          <th><%= PriceByDistance.human_attribute_name(:distance_tax)%></th>
        </tr>
      </thead>
      <tbody>
        <% @price_by_distances.each do | price_by_distance | %>
        <tr>
          <td><%= price_by_distance.start_range %> km</td>
          <td><%= price_by_distance.end_range %> km</td>
          <td>  <%=  number_to_currency(price_by_distance.distance_tax, unit: "R$", separator: ",")%> </td>
          <% if current_user.admin? %>
            <td> <%= link_to 'Editar', edit_price_by_distance_path(price_by_distance) %> </td>
            <td> <%= button_to 'Remover', price_by_distance_path(price_by_distance), method: :delete, class:"btn btn-dark" %> </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nao existem preços por distância cadastrados.</p>
  <% end %>
</div>

<h3>Preço por Peso</h3>

<% if !flash[:price_by_weight_errors].nil? %>
  <p> Verifique os erros abaixo: </p>
  <ul>
    <% flash[:price_by_weight_errors].each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<div class="price_by_weight" id="form">
  <% if current_user.admin? %>
    <%= form_with(model: @price_by_weight) do | pw |%>
      <%= pw.hidden_field :transport_model_id, value: @transport_model.id, readonly: true %>
      <div class="mb-3">
        <%= pw.label :start_range %>
        <%= pw.number_field :start_range%>
      </div>
      <div class="mb-3">
        <%= pw.label :end_range %>
        <%= pw.number_field :end_range %>
      </div>
      <div class="mb-3">
        <%= pw.label :price_for_kg%>
        <%= pw.number_field :price_for_kg, step: 0.10 %>
      </div>
      <div class="mb-3">
        <%= pw.submit 'Cadastrar Preço por Peso', class:"btn btn-dark" %>
      </div>
    <% end %>
  <% end %>
</div>

<div>
  <% if @price_by_weights.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th> <%= PriceByWeight.human_attribute_name(:start_range)%></th>
          <th><%= PriceByWeight.human_attribute_name(:end_range)%></th>
          <th><%= PriceByWeight.human_attribute_name(:price_for_kg)%></th>
        </tr>
      </thead>
      <tbody>
        <% @price_by_weights.each do | price_by_weight | %>
        <tr>
          <td><%= price_by_weight.start_range %> kg</td>
          <td><%= price_by_weight.end_range %> kg</td>
          <td> <%= number_to_currency(price_by_weight.price_for_kg, unit: "R$", separator: ",")%> </td>
          <% if current_user.admin? %>
            <td> <%= link_to 'Editar', edit_price_by_weight_path(price_by_weight) %> </td>
            <td> <%= button_to 'Remover', price_by_weight_path(price_by_weight), method: :delete, class:"btn btn-dark" %> </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nao existem preços por peso cadastrados.</p>
  <% end %>
</div>

<h3>Prazo Estimado de Entrega por Distância</h3>


<% if !flash[:delivery_time_table_errors].nil? %>
  <p> Verifique os erros abaixo: </p>
  <ul>
    <% flash[:delivery_time_table_errors].each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>


<div class="delivery_time_table" id="form">
  <% if current_user.admin? %>
    <%= form_with(model: @delivery_time_table, url: delivery_time_table_index_path) do | dt |%>
      <%= dt.hidden_field :transport_model_id, value: @transport_model.id, readonly: true %>
      <div class="mb-3">
        <%= dt.label :start_range %>
        <%= dt.number_field :start_range%>
      </div>
      <div class="mb-3">
        <%= dt.label :end_range %>
        <%= dt.number_field :end_range %>
      </div>
      <div class="mb-3">
        <%= dt.label :delivery_time%>
        <%= dt.number_field :delivery_time %>
      </div>
      <div class="mb-3">
        <%= dt.submit "Cadastrar #{DeliveryTimeTable.human_attribute_name(:delivery_time)}", class:"btn btn-dark" %>
      </div>
    <% end %>
  <% end %>
</div>

<div>
  <% if @delivery_times_table.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th> <%= DeliveryTimeTable.human_attribute_name(:start_range)%></th>
          <th><%= DeliveryTimeTable.human_attribute_name(:end_range)%></th>
          <th><%= DeliveryTimeTable.human_attribute_name(:delivery_time)%></th>
        </tr>
      </thead>
      <tbody>
        <% @delivery_times_table.each do | delivery_time_row | %>
        <tr>
          <td><%= delivery_time_row.start_range %> km</td>
          <td><%= delivery_time_row.end_range %> km</td>
          <td><%= delivery_time_row.delivery_time %> h </td>
          <% if current_user.admin? %>
            <td> <%= link_to 'Editar', edit_delivery_time_table_path(delivery_time_row) %> </td>
            <td> <%= button_to 'Remover', delivery_time_table_path(delivery_time_row), method: :delete, class:"btn btn-dark" %> </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nao existem estimativa de prazos cadastrados.</p>
  <% end %>
</div>