config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :transport_models, only: %i[index new create show edit update show] do
    patch 'change_status', on: :member
  end
  resources :vehicles, only: %i[index new create update edit show] do
    get 'search', on: :collection
  end
  resources :price_by_distances, only: %i[new create edit update destroy]
  resources :price_by_weights, only: %i[new create edit update destroy]
  resources :delivery_time_table, only: %i[new create edit update destroy]
  resources :service_orders, only: %i[index new create show] do
    get 'search', on: :collection
    scope module: :service_orders, as: 'service_orders' do
      collection do
        resources :process, only: %i[index create edit]
        resources :deliver, only: %i[index create edit]
      end
    end
  end
end

app/models/service_order.rb
# frozen_string_literal: true

class ServiceOrder < ApplicationRecord
  belongs_to :transport_model, optional: true
  belongs_to :vehicle, optional: true
  belongs_to :customer
  has_one :product
  accepts_nested_attributes_for :customer, :product

  enum service_order_status: { pending: 0, processed: 5, delivered: 10 }
  enum delivery_status: { on_time: 0, with_delay: 10 }

  validates :pickup_address, :pickup_cep, :delivery_distance, presence: true
  validates :delivery_distance, numericality: { greater_than_or_equal_to: 0 }
  validates :pickup_cep, length: { is: 8 }
  validates :pickup_cep, numericality: { only_integer: true }
  validates :delivery_description, presence: true, if: -> { with_delay? }

  scope :search, ->(query) {
    if query.present?
      where(
        'code LIKE :query OR pickup_address LIKE :query OR pickup_cep LIKE :query',
        query: "%#{query}%"
      )
    end
  }

  before_create :generate_code

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15)
  end
end

app/models/service_orders/deliver.rb
# frozen_string_literal: true

module ServiceOrders
  class Deliver
    attr_reader :service_order, :params

    def self.perform(service_order, params)
      new(service_order, params).perform
    end

    def initialize(service_order, params)
      @service_order = service_order
      @params = params
    end

    def perform
      service_order.delivery_description = params[:delivery_description]
      service_order.delivery_date = Time.zone.now
      service_order.delivery_status = delivery_status
      service_order.service_order_status = :delivered
      service_order.vehicle.waiting!
      if service_order.save
        [true, []]
      else
        [false, service_order.errors.full_messages]
      end
    end

    private

    def delivery_status
      if service_order.estimated_delivery_date < Time.zone.now
        :with_delay
      else
        :on_time
      end
    end
  end
end

app/models/service_orders/processor.rb
# frozen_string_literal: true

module ServiceOrders
  class Processor
    attr_reader :service_order, :transport_model

    def self.perform(service_order, transport_model)
      new(service_order, transport_model).perform
    end

    def initialize(service_order, transport_model)
      @service_order = service_order
      @transport_model = transport_model
    end

    def perform
      service_order.estimated_delivery_date = calculate_estimated_delivery_date
      service_order.processed_date = Time.zone.now
      service_order.vehicle = vehicle
      service_order.transport_model = transport_model
      service_order.delivery_price = calculate_shipping_price
      service_order.processed!
      vehicle.active!
    end

    private

    def calculate_estimated_delivery_date
      delivery_time = transport_model.delivery_time(service_order.delivery_distance)
      Time.zone.now + delivery_time.hours
    end

    def vehicle
      transport_model.vehicles.waiting.first
    end

    def calculate_shipping_price
      transport_model.shipping_price(service_order.product.weight, service_order.delivery_distance)
    end
  end
end

app/controllers/service_orders/deliver_controller.rb
# frozen_string_literal: true

module ServiceOrders
  class DeliverController < ApplicationController
    before_action :authenticate_user!

    def index
      @service_orders = ServiceOrder.processed
    end

    def edit
      @service_order = ServiceOrder.find(params[:id])
    end

    def create
      @service_order = ServiceOrder.find(params[:id])

      success, errors = ServiceOrders::Deliver.perform(@service_order, service_order_params)
      if success
        flash[:notice] = 'Ordem de Serviço encerrada com sucesso.'
        redirect_to service_order_path(@service_order)
      else
        flash = { notice: 'Não foi possível encerrar ordem de serviço.', service_order_errors: errors }
        redirect_to edit_service_orders_deliver_path(@service_order), flash:
      end
    end

    private

    def service_order_params
      params.require(:service_order).permit(:delivery_description)
    end
  end
end

app/controllers/service_orders/process_controller.rb
# frozen_string_literal: true

module ServiceOrders
  class ProcessController < ApplicationController
    before_action :authenticate_user!

    def index
      @service_orders = ServiceOrder.pending
    end

    def create
      @service_order = ServiceOrder.find(params[:id])
      transport_model = TransportModel.find(params[:service_order][:transport_model_id])
      if ServiceOrders::Processor.perform(@service_order, transport_model)
        flash[:notice] = 'Ordem de Serviço processada com sucesso.'
        redirect_to service_order_path(@service_order)
      else
        flash.now[:notice] = 'Não foi possível processar a ordem de serviço.'
        redirect_to edit_service_orders_process_path(@service_order)
      end
    end

    def edit
      @service_order = ServiceOrder.find(params[:id])
      @available_transport_models = TransportModel.by_distance(@service_order.delivery_distance).with_vehicles_available.active
    end

    private

    def service_order_params
      params.require(:service_order).permit(
        :transport_model_id
      )
    end
  end
end

app/controllers/service_orders_controller.rb
# frozen_string_literal: true

class ServiceOrdersController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create show]

  def index
    @service_orders = ServiceOrder.search(params[:query]).sort_by(&:service_order_status)
  end

  def new
    @service_order = ServiceOrder.new
  end

  def create
    @service_order = ServiceOrder.new(service_order_params)

    if @service_order.save
      flash[:notice] = 'Ordem de Serviço cadastrada com sucesso.'
      redirect_to service_order_path(@service_order)
    else
      flash.now[:notice] = 'Ordem de Serviço não cadastrada.'
      render 'new'
    end
  end

  def show
    @service_order = ServiceOrder.find(params[:id])
  end

  def search
    @query = params[:query]
    @service_order = ServiceOrder.find_by(code: @query)
  end

  private

  def service_order_params
    params.require(:service_order).permit(
      :pickup_address, :pickup_cep,
      :delivery_distance,
      product_attributes: %i[length width height weight],
      customer_attributes: %i[customer_address customer_cep customer_name customer_registration_number]
    )
  end
end

app/views/service_orders/_form.html.erb
<%= form_for(@service_order) do |f| %>
  <div class="mb-3">
    <%= f.label :pickup_address %>
    <%= f.text_field :pickup_address %>
  </div>
  <div class="mb-3">
    <%= f.label :pickup_cep %>
    <%= f.text_field :pickup_cep %>
  </div>
  <div class="mb-3">
    <%= f.label :delivery_distance %>
    <%= f.number_field :delivery_distance, step: 0.1 %>
  </div>

  <%= f.fields_for :customer, Customer.new do |customer_subform| %>
    <div class="mb-3">
      <%= customer_subform.label :customer_address, Customer.human_attribute_name(:customer_address) %>
      <%= customer_subform.text_field :customer_address %>
    </div>
    <div class="mb-3">
      <%= customer_subform.label :customer_cep, Customer.human_attribute_name(:customer_cep) %>
      <%= customer_subform.text_field :customer_cep %>
    </div>
    <div class="mb-3">
      <%= customer_subform.label :customer_name, Customer.human_attribute_name(:customer_name) %>
      <%= customer_subform.text_field :customer_name %>
    </div>
    <div class="mb-3">
      <%= customer_subform.label :customer_registration_number, Customer.human_attribute_name(:customer_registration_number) %>
      <%= customer_subform.text_field :customer_registration_number %>
    </div>
  <% end %>

    <%= f.fields_for :product, Product.new do |builder| %>
    <div class="mb-3">
      <%= builder.label :length, Product.human_attribute_name(:length) %>
      <%= builder.number_field :length %>
    </div>
    <div class="mb-3">
      <%= builder.label :width, Product.human_attribute_name(:width) %>
      <%= builder.number_field :width %>
    </div>
    <div class="mb-3">
      <%= builder.label :height, Product.human_attribute_name(:height) %>
      <%= builder.number_field :height %>
    </div>
    <div class="mb-3">
      <%= builder.label :weight, Product.human_attribute_name(:weight) %>
      <%= builder.number_field :weight %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.submit 'Cadastrar Ordem de Serviço' %>
  </div>
<% end %>

app/views/service_orders/index.html.erb
<h2> <%=ServiceOrder.model_name.human%></h2>

<nav>
  <% if current_user.admin? %>
    <%= link_to 'Cadastrar nova ordem de serviço', new_service_order_path %>
  <% end %>
  <% if current_user.regular_user? %>
    <%= link_to 'Pendentes', service_orders_process_index_path %> |
    <%= link_to 'Processadas', service_orders_deliver_index_path %>
  <% end %>
</nav>

<%= form_with(url: service_orders_path, method: :get) do | f |%>
  <%= f.label :query,  'Buscar Ordem de Serviço' %>
  <%= f.text_field :query %>
  <%= f.submit 'Buscar' %>
<% end %>

<% if @service_orders.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= ServiceOrder.human_attribute_name(:code)%> </th>
        <th><%= ServiceOrder.human_attribute_name(:pickup_address)%><br>(CEP)<br></th>
        <th><%= Customer.human_attribute_name(:customer_address)%></th>
        <th><%= ServiceOrder.human_attribute_name(:delivery_distance)%></th>
        <th><%= ServiceOrder.human_attribute_name(:service_order_status)%></th>
        <% if current_user.regular_user? %>
          <th>Ações</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @service_orders.each do | service_order | %>
      <tr>
        <td> <%= link_to service_order.code, service_order %></td>
        <td> <%= service_order.pickup_address %><br>(<%= cep_formatted(service_order.pickup_cep) %>)<br></td>
        <td> <%= service_order.customer.customer_address %><br>(<%= cep_formatted(service_order.customer.customer_cep) %>)<br></td>
        <td> <%= number_with_precision(service_order.delivery_distance, precision: 2, separator: ',') %> km</td>
        <td> <%= I18n.t(service_order.service_order_status) %></td>
        <% if current_user.regular_user? %>
          <% if service_order.pending? %>
            <td> <%= link_to 'Alocar Modalidade de Transporte', edit_service_orders_process_path(service_order) %></td>
          <% elsif service_order.processed? %>
            <td> <%= link_to 'Encerrar', edit_service_orders_deliver_path(service_order) %></td>
          <% end %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p>Nao existem ordens de serviço cadastradas.</p>
<% end %>

app/views/service_orders/new.html.erb
<h1> Nova Ordem de Serviço </h1>

<% if @service_order.errors.any? %>
  <p> Verifique os erros abaixo: </p>

  <ul>
    <% @service_order.errors.full_messages.each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/service_orders/search.html.erb
<h2> Código de Rastreio: <%= @service_order&.code %> </h2>

<% if @service_order.nil? %>
  <p>Sem resultado para a busca.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th><%= ServiceOrder.human_attribute_name(:pickup_address) %></th>
        <th><%= Customer.human_attribute_name(:customer_address) %></th>
        <th><%= ServiceOrder.human_attribute_name(:service_order_status) %></th>
        <% if !@service_order.pending? %>
          <th><%= ServiceOrder.human_attribute_name(:processed_date) %></th>
          <th><%= Vehicle.human_attribute_name(:identification_plate) %> do Veículo</th>
          <th><%= Vehicle.human_attribute_name(:vehicle_type) %> do Veículo</th>
          <% if @service_order.delivered? %>
            <th><%= ServiceOrder.human_attribute_name(:delivery_date) %></th>
            <% if @service_order.with_delay? %>
              <th><%= ServiceOrder.human_attribute_name(:delivery_description) %></th>
            <% end %>
          <% else %>
            <th><%= ServiceOrder.human_attribute_name(:estimated_delivery_date) %></th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @service_order.pickup_address %> </td>
        <td><%= @service_order.customer.customer_address %> </td>
        <td><%= I18n.t(@service_order.service_order_status) %> </td>
        <% if !@service_order.pending? %>
          <td><%= @service_order.processed_date&.strftime('%d/%m/%Y %H h') %></td>
          <td><%= @service_order.vehicle.identification_plate %> </td>
          <td><%= @service_order.vehicle.vehicle_type %></td>
          <% if @service_order.delivered? %>
            <td><%= @service_order.delivery_date.strftime('%d/%m/%Y %H h') %></th>
            <% if @service_order.with_delay? %>
              <td><%= @service_order.delivery_description %></td>
            <% end %>
          <% else %>
            <td><%= @service_order.estimated_delivery_date.strftime('%d/%m/%Y %H h') %> </td>
          <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/service_orders/show.html.erb
<h2> <%= ServiceOrder.model_name.human %>: <%= @service_order.code %></h2>

<div>
  <dl>
    <dt> <%= ServiceOrder.human_attribute_name(:pickup_address) %>:</dt>
    <dd> <%= @service_order.pickup_address %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:pickup_cep) %>:</dt>
    <dd> <%= cep_formatted(@service_order.pickup_cep) %></dd>
    <dt> Dimensões do Produto (C x L x A):</dt>
    <dd> <%= @service_order.product.length%>cm x <%= @service_order.product.width%>cm x <%= @service_order.product.height%>cm</dd>
    <dt> <%= Product.human_attribute_name(:weight) %>:</dt>
    <dd> <%= number_with_precision(@service_order.product.weight, precision: 2, separator: ',') %>kg</dd>
    <dt> <%= Customer.human_attribute_name(:customer_address) %>:</dt>
    <dd> <%= @service_order.customer.customer_address %></dd>
    <dt> <%= Customer.human_attribute_name(:customer_cep) %>:</dt>
    <dd> <%= cep_formatted(@service_order.customer.customer_cep) %></dd>
    <dt> <%= Customer.human_attribute_name(:customer_name) %>:</dt>
    <dd> <%= @service_order.customer.customer_name %></dd>
    <dt> <%= Customer.human_attribute_name(:customer_cpf) %>:</dt>
    <dd> <%= formatted_cpf(@service_order.customer.customer_registration_number) %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:delivery_distance) %>:</dt>
    <dd> <%= number_with_precision(@service_order.delivery_distance, precision: 2, separator: ',') %> km</dd>
    <dt> <%= ServiceOrder.human_attribute_name(:service_order_status) %>:</dt>
    <dd> <%= I18n.t(@service_order.service_order_status) %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:processed_date) %>:</dt>
    <dd> <%= @service_order.processed_date&.strftime('%d/%m/%Y %H h') %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:transport_model) %>:</dt>
    <dd> <%= @service_order.transport_model&.name %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:estimated_delivery_date) %>:</dt>
    <dd> <%= @service_order.estimated_delivery_date&.strftime('%d/%m/%Y %H h') %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:vehicle) %>:</dt>
    <dd> <%= @service_order.vehicle&.identification_plate %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:delivery_date) %>:</dt>
    <dd> <%= @service_order.delivery_date&.strftime('%d/%m/%Y %H h') %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:delivery_status) %>:</dt>
    <dd> <%= I18n.t(@service_order.delivery_status) %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:delivery_description) %>:</dt>
    <dd> <%= @service_order&.delivery_description %></dd>
    <dt> <%= ServiceOrder.human_attribute_name(:delivery_price) %>:</dt>
    <dd> <%= number_to_currency(@service_order&.delivery_price, unit: "R$", precision: 2, separator: ',') %></dd>
  </dl>
</div>