config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :transport_models, only: %i[index new create show edit update show] do
    patch 'change_status', on: :member
  end
  resources :vehicles, only: %i[index new create update edit show] do
    get 'search', on: :collection
  end
  resources :price_by_distances, only: %i[new create edit update destroy]
  resources :price_by_weights, only: %i[new create edit update destroy]
  resources :delivery_time_table, only: %i[new create edit update destroy]
  resources :service_orders, only: %i[index new create show] do
    get 'search', on: :collection
    scope module: :service_orders, as: 'service_orders' do
      collection do
        resources :process, only: %i[index create edit]
        resources :deliver, only: %i[index create edit]
      end
    end
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  enum status: { waiting: 0, active: 5, maintenance: 10 }
  belongs_to :transport_model
  validates :identification_plate, :vehicle_brand, :vehicle_type, :fabrication_year, :max_load_capacity, presence: true
  validates :fabrication_year, :max_load_capacity,
            numericality: { greater_than_or_equal_to: 0, message: 'não pode ser negativa' }
  validates :identification_plate, length: { is: 7 }, uniqueness: true
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle, only: %i[edit update show]

  def index
    @vehicles = Vehicle.all.in_order_of(:status, [5, 0, 10])
  end

  def new
    @vehicle = Vehicle.new
    @transport_models = TransportModel.all
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to vehicles_path, notice: 'Veículo cadastrado com sucesso.'
    else
      @transport_models = TransportModel.all
      flash.now[:alert] = 'Veículo não cadastrado.'
      render 'new'
    end
  end

  def update
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path, notice: 'Veículo atualizado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar veículo.'
      @transport_models = TransportModel.all
      render 'edit'
    end
  end

  def edit
    @transport_models = TransportModel.all
  end

  def show; end

  def search
    @query = params[:query]
    @vehicles = Vehicle.where(
      'identification_plate LIKE ? OR vehicle_brand LIKE ? OR vehicle_type LIKE ?
      OR fabrication_year LIKE ? OR max_load_capacity LIKE ? OR transport_model_id LIKE ?', "%#{@query}%",
      "%#{@query}%", "%#{@query}%", "%#{@query}%", "%#{@query}%", "%#{@query}%"
    )
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(
      :identification_plate, :vehicle_brand, :vehicle_type,
      :fabrication_year, :max_load_capacity, :transport_model_id, :status
    )
  end
end

app/helpers/vehicle_helper.rb
# frozen_string_literal: true

module VehicleHelper
  def changeable_status(status)
    Vehicle.statuses.keys - [status]
  end
end

app/views/vehicles/_form.html.erb
<%= form_with(model: @vehicle) do | v |%>
  <div class="mb-3">
    <%= v.label :identification_plate %>
    <%= v.text_field :identification_plate%>
  </div>
  <div class="mb-3">
    <%= v.label :vehicle_brand %>
    <%= v.text_field :vehicle_brand%>
  </div>
  <div class="mb-3">
    <%= v.label :vehicle_type %>
    <%= v.text_field :vehicle_type%>
  </div>
  <div class="mb-3">
    <%= v.label :fabrication_year %>
    <%= v.number_field :fabrication_year%>
  </div>
  <div class="mb-3">
    <%= v.label :max_load_capacity %>
    <%= v.number_field :max_load_capacity%>
  </div>
  <div class="mb-3">
    <%= v.label :transport_model_id %>
    <%= v.collection_select :transport_model_id, @transport_models, :id, :name %>
  </div>
  <div class="mb-3">
    <%= v.submit 'Cadastrar'%>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h2> Editar Veículo</h2>

<% if @vehicle.errors.any? %>
  <p> Verifique os erros abaixo: </p>

  <ul>
    <% @vehicle.errors.full_messages.each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/vehicles/index.html.erb
<h2> <%=Vehicle.model_name.human(:count => 2)%></h2>
<nav>
  <% if current_user.admin? %>
    <%= link_to 'Cadastrar novo veículo', new_vehicle_path %>
  <% end %>
</nav>

<% if @vehicles.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th><%= Vehicle.human_attribute_name(:identification_plate)%></th>
        <th><%= Vehicle.human_attribute_name(:vehicle_brand)%></th>
        <th><%= Vehicle.human_attribute_name(:vehicle_type)%></th>
        <th><%= Vehicle.human_attribute_name(:fabrication_year)%></th>
        <th><%= Vehicle.human_attribute_name(:max_load_capacity)%></th>
        <th><%= TransportModel.model_name.human %></th>
        <th><%= Vehicle.human_attribute_name(:status)%></th>
        <% if current_user.admin? %>
          <th> Ações </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do | vehicle | %>
        <tr>
          <td><%= link_to vehicle.identification_plate, vehicle_path(vehicle) %> </td>
          <td><%= vehicle.vehicle_brand %> </td>
          <td><%= vehicle.vehicle_type %> </td>
          <td><%= vehicle.fabrication_year %> </td>
          <td><%= vehicle.max_load_capacity %>kg</td>
          <td><%= vehicle.transport_model.name %> </td>
          <td><%= I18n.t(vehicle.status) %> </td>
          <% if current_user.admin? %>
            <% array_status = changeable_status(vehicle.status) %>
            <% array_status.each do | status | %>
              <td> <%= button_to I18n.t(status), vehicle_path(vehicle.id, vehicle: {status:status}), method: :patch, class:"btn btn-dark" %> </td>
            <% end %>
            <td> <%= link_to 'Editar', edit_vehicle_path(vehicle.id)%> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nao existem veículos cadastrados.</p>
<% end %>

app/views/vehicles/new.html.erb
<h1> Novo Veículo de Transporte </h1>

<% if @vehicle.errors.any? %>
  <p> Verifique os erros abaixo: </p>

  <ul>
    <% @vehicle.errors.full_messages.each do | msg |%>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= render 'form'%>

app/views/vehicles/search.html.erb
<h2> <%=Vehicle.model_name.human(:count => 2)%></h2>

<p><%= @vehicles.count %> <%= Vehicle.model_name.human(count:@vehicles.count).downcase %> <%= t(:found, count: @vehicles.count) %></p>
<% if @vehicles.any? %>
  <table>
    <thead>
      <tr>
        <th><%= Vehicle.human_attribute_name(:identification_plate)%></th>
        <th><%= Vehicle.human_attribute_name(:vehicle_brand)%></th>
        <th><%= Vehicle.human_attribute_name(:vehicle_type)%></th>
        <th><%= Vehicle.human_attribute_name(:fabrication_year)%></th>
        <th><%= Vehicle.human_attribute_name(:max_load_capacity)%></th>
        <th><%= TransportModel.model_name.human %></th>
        <th><%= Vehicle.human_attribute_name(:status)%></th>
      </tr>
    </thead>
    <tbody>
      <% @vehicles.each do | v | %>
      <tr>
        <td><%= v.identification_plate %> </td>
        <td><%= v.vehicle_brand %> </td>
        <td><%= v.vehicle_type %> </td>
        <td><%= v.fabrication_year %> </td>
        <td><%= v.max_load_capacity %>kg</td>
        <td><%= v.transport_model.name %> </td>
        <td><%= I18n.t(v.status) %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sem resultado para a busca.</p>
<% end %>

app/views/vehicles/show.html.erb
<h2> <%= Vehicle.model_name.human %>: <%=@vehicle.identification_plate%></h2>

<div>
  <dl>
    <dt> <%= Vehicle.human_attribute_name(:identification_plate) %></dt>
    <dd> <%= @vehicle.identification_plate %></dd>
    <dt> <%= Vehicle.human_attribute_name(:vehicle_brand) %> </dt>
    <dd> <%= @vehicle.vehicle_brand %></dd>
    <dt> <%= Vehicle.human_attribute_name(:vehicle_type) %> </dt>
    <dd> <%= @vehicle.vehicle_type %></dd>
    <dt> <%= Vehicle.human_attribute_name(:fabrication_year) %> </dt>
    <dd> <%= @vehicle.fabrication_year %></dd>
    <dt> <%= Vehicle.human_attribute_name(:max_load_capacity) %> </dt>
    <dd> <%= @vehicle.max_load_capacity %></dd>
    <dt> <%= TransportModel.model_name.human %> </dt>
    <dd> <%= @vehicle.transport_model.name  %></dd>
    <dt> <%= Vehicle.human_attribute_name(:status) %> </dt>
    <dd> <%= I18n.t(@vehicle.status) %></dd>
  </dl>
</div>